name: "🐛 Issue Fix"
description: "버그 수정 또는 이슈 해결"
labels: ["bugfix"]
body:
  - type: textarea
    attributes:
      label: 🚨 문제 상황
      description: 어떤 문제가 발생했는지 설명해 주세요.
      placeholder: 에러 메시지, 로그, 재현 방법 등을 포함하면 좋아요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔍 원인 분석
      description: 원인을 파악한 경우, 분석 내용을 작성해 주세요.
      placeholder: 코드 상의 문제, 로직 오류, 환경 설정 문제 등
  - type: textarea
    attributes:
      label: 🛠 해결 방법
      description: 문제를 어떻게 해결했는지 작성해 주세요.
      placeholder: 수정한 파일, 로직, 테스트 방법 등
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 관련 이슈나 문서 링크가 있다면 작성해 주세요.
